# Generated by Django 6.0.6 on 2026-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='photos/cover.jpg', upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='photos/default.jpg', upload_to='profile_pics/'),
        ),
    ]
